# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
            options={
                'db_table': 'app_categories',
            },
        ),
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_proxies',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('negative', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=1)),
                ('total_ads', models.IntegerField(default=0)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Proxies')),
            ],
            options={
                'db_table': 'app_search_log',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Stopped'), (3, 'Completed')], default=1)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_tasks', to='app.SearchLog')),
            ],
            options={
                'db_table': 'app_tasks',
            },
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('search_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_websites',
            },
        ),
        migrations.AddField(
            model_name='searchlog',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Websites'),
        ),
        migrations.AddField(
            model_name='categories',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Websites'),
        ),
    ]
