# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('posted_on', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, default=0, null=True)),
                ('created_time', models.DateTimeField(blank=True)),
                ('modified_time', models.DateTimeField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'VISIBLE'), (1, 'SOFT DELETE'), (3, 'INVALID')], default=1)),
            ],
            options={
                'db_table': 'app_fetched_ads',
            },
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Stopped'), (4, 'Completed'), (5, 'Error')], default=1),
        ),
        migrations.AddField(
            model_name='fetchedads',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetched_ads', to='app.Tasks'),
        ),
    ]
