# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fetchedads_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedads',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
